import Config

# Configure your database
# Priority:
# 1. RAILWAY_DATABASE_URL (for Railway TCP proxy connection - manually set)
# 2. DATABASE_PUBLIC_URL (Railway's public proxy URL if TCP proxy is enabled)
# 3. DATABASE_URL (standard database URL - may use internal Railway domain)
# 4. Local PostgreSQL (fallback)
cond do
  System.get_env("RAILWAY_DATABASE_URL") != nil ->
    # Use Railway database via TCP proxy (manually configured)
    database_url = System.get_env("RAILWAY_DATABASE_URL")
    # Add SSL mode if not present
    database_url =
      if String.contains?(database_url, "sslmode"),
        do: database_url,
        else: "#{database_url}?sslmode=require"

    config :railway_app, RailwayApp.Repo,
      url: database_url,
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: String.to_integer(System.get_env("POOL_SIZE") || "20")

  System.get_env("DATABASE_PUBLIC_URL") != nil ->
    # Use Railway's public database URL (when TCP proxy is enabled)
    database_url = System.get_env("DATABASE_PUBLIC_URL")
    # Add SSL mode if not present
    database_url =
      if String.contains?(database_url, "sslmode"),
        do: database_url,
        else: "#{database_url}?sslmode=require"

    config :railway_app, RailwayApp.Repo,
      url: database_url,
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: String.to_integer(System.get_env("POOL_SIZE") || "20")

  System.get_env("DATABASE_URL") != nil ->
    # Use provided DATABASE_URL (may be internal Railway domain - won't work locally)
    database_url = System.get_env("DATABASE_URL")

    # Check if it's an internal Railway domain (won't work locally)
    if String.contains?(database_url, "railway.internal") do
      IO.warn("""
      ⚠️  WARNING: DATABASE_URL uses Railway internal domain (postgres.railway.internal)
      This will not work for local development. Please either:
      1. Enable TCP Proxy in Railway Dashboard and use DATABASE_PUBLIC_URL, or
      2. Set RAILWAY_DATABASE_URL with the proxy connection string
      """)
    end

    config :railway_app, RailwayApp.Repo,
      url: database_url,
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: String.to_integer(System.get_env("POOL_SIZE") || "20")

  true ->
    # Use local PostgreSQL
    config :railway_app, RailwayApp.Repo,
      username: "postgres",
      password: "postgres",
      hostname: "localhost",
      database: "railway_app_dev",
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :railway_app, RailwayAppWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "dev-only-secret-key-base-replace-in-production-with-mix-phx-gen-secret",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:railway_app, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:railway_app, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :railway_app, RailwayAppWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$"E,
      ~r"priv/gettext/.*(po)$",
      ~r"lib/railway_app_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :railway_app, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Local development configuration - no Railway integration
# Railway integration is disabled for local development to avoid network issues

# Optional: Slack integration (only if SLACK_BOT_TOKEN is set)
if System.get_env("SLACK_BOT_TOKEN") do
  config :railway_app, :slack,
    bot_token: System.get_env("SLACK_BOT_TOKEN"),
    signing_secret: System.get_env("SLACK_SIGNING_SECRET"),
    channel_id: System.get_env("SLACK_CHANNEL_ID")
end

# Local LLM configuration
config :railway_app, :llm,
  default_provider: System.get_env("LLM_DEFAULT_PROVIDER") || "openai",
  openai_api_key: System.get_env("OPENAI_API_KEY"),
  anthropic_api_key: System.get_env("ANTHROPIC_API_KEY")

# Railway integration for local development (optional)
# Set RAILWAY_API_TOKEN environment variable to connect to real Railway services
config :railway_app, :railway,
  api_token: System.get_env("RAILWAY_API_TOKEN"),
  project_id: System.get_env("RAILWAY_PROJECT_ID"),
  environment_id: System.get_env("RAILWAY_ENVIRONMENT_ID"),
  graphql_endpoint:
    System.get_env("RAILWAY_GRAPHQL_ENDPOINT") || "https://backboard.railway.app/graphql/v2",
  websocket_endpoint:
    System.get_env("RAILWAY_WS_ENDPOINT") || "wss://backboard.railway.app/graphql/v2"
